### ISSUE TITLE
fully charged/empty in counts should show hrs and mins if mins > 60

### ISSUE THREAD

**Issue by Steffan153** [max-programming/battery-info-javascript#2]
like this:
![image](https://user-images.githubusercontent.com/40404519/97628193-fc8f6200-19f1-11eb-8238-3b8d86520c3b.png)
it should say 1h 6min, not 66min

**Comment by max-programming** [comment]
Okay! Will work on it if I get time today. Thanks for creating the issue.

**Comment by max-programming** [comment]
@Steffan153 Can you please solve this issue? Because I don't have a laptop and I can't resolve it

**Comment by Steffan153** [comment]
Yes, I can. Just curious what happened with your laptop? Stop working?

**Comment by max-programming** [comment]
> Yes, I can. Just curious what happened with your laptop? Stop working?

I don't have a laptop now. I have a PC 😂. 
Thanks

**Comment by Steffan153** [comment]
Ah, you mean a desktop? I thought most laptops were PCs XD

**Comment by max-programming** [comment]
Yeah lol
