### ISSUE TITLE
Remove bootstrap?

### ISSUE THREAD

**Issue by Steffan153** [max-programming/battery-info-javascript#3]
Bootstrap here doesn't really do _that_ much, wouldn't it make sense to remove it? We could even replace it with Tailwind, ofc plain CSS is also fine for me.

**Comment by max-programming** [comment]
I actually use the Darkly theme from bootswatch. Which makes it look better: https://bootswatch.com/darkly/
What do you think if we replace it with tailwind.

**Comment by Steffan153** [comment]
Tailwind sounds great, but the CDN is resource-heavy, so if we do then please with the build process, to have tree-shaking.

I'm not complaining about the look btw lol, it's just that bootstrap seems like a waste of performance lol.

**Comment by max-programming** [comment]
Hmmm. I am on a holiday today. So I'll come back here tomorrow. btw thanks for suggesting this. We can maybe use plain css instead of bootstrap which we use now. we'll write the classes.

**Comment by Steffan153** [comment]
So are you planning on doing this or do you want me to work on it?

**Comment by max-programming** [comment]
@Steffan153 If you want, you can, because it is an easy task. So, I can assign this to you if you want.

**Comment by Steffan153** [comment]
Well, if you want to do it then sure, do it. But I can do it if you want.

**Comment by max-programming** [comment]
I will do it. There's just some time to put in. Thanks for the issue

**Comment by max-programming** [comment]
But @Steffan153 , i am using the progressbar by bootstrap. How can we replicate that

**Comment by Steffan153** [comment]
of course you'll wanna customize this more but this seems good https://stackoverflow.com/a/58163874

**Comment by Steffan153** [comment]
here ya go, pretty much the same now https://jsfiddle.net/jkd82om4/

**Comment by max-programming** [comment]
Did you remake it? Looks exactly similar! Thanks

**Comment by Steffan153** [comment]
I took the code from the stackoverflow and just modified it a little bit

**Comment by max-programming** [comment]
lol. We are stackoverflowians

**Comment by max-programming** [comment]
@Steffan153 I removed Bootstrap and I think now it takes a long time to tell the display the battery percentage

**Comment by Steffan153** [comment]
Wdym?
Dm me on Twitter so we can figure this out.

**Comment by max-programming** [comment]
> Wdym?
> Dm me on Twitter so we can figure this out.

Just check it on your phone. Does it take a bit time to show the battery level? Or is it instant?

**Comment by Steffan153** [comment]
It's instant in both android chrome and desktop edge.

**Comment by max-programming** [comment]
Okay! I get it now. I was trying it on the mobile version of Edge which took time. Thanks for your help @Steffan153
