### ISSUE TITLE
Doesn't work on Windows edge sometimes?

### ISSUE THREAD

**Issue by Steffan153** [max-programming/battery-info-javascript#4]
not sure what, it works fine on my Linux, but
![image](https://user-images.githubusercontent.com/40404519/97757406-434c8d00-1ac2-11eb-9960-78be83262fdd.png)

**Comment by max-programming** [comment]
Ohh. I need to check. Thanks for creating the issue. Which build is it?

**Comment by Steffan153** [comment]
88.0.680.1

**Comment by Steffan153** [comment]
The interesting thing is that getBattery exists, but it just got overrid to undefined.

**Comment by max-programming** [comment]
Okay. The Dev Build Thanks!

**Comment by Steffan153** [comment]
Yeah, the normal build doesn't have the vertical tabs yet, if you noticed lol

**Comment by max-programming** [comment]
But it works fine on my end. Try it in the InPrivate window and let me know

**Comment by Steffan153** [comment]
Well, I just tried again and it works fine now ¯\\\_(ツ)_/¯

Sorry

**Comment by max-programming** [comment]
NP lol
